import { Mail, ScanSearch, Route, Workflow } from 'lucide-react';
import { Scenario } from './types';

export const scenarios: Scenario[] = [
  {
    id: 'leads',
    title: 'Leads sin seguimiento',
    subtitle: 'Formulario, email e Instagram entrando por separado',
    problem: 'El equipo tarda horas en contestar y nadie sabe que oportunidad merece prioridad comercial.',
    inputLabel: 'Mensajes web, email e Instagram',
    outputLabel: 'Lead score, resumen y tarea comercial',
    impact: 'Reduce tiempo de respuesta y evita que las oportunidades buenas se queden en una cola opaca.',
    assistantPrompt: 'Leo intencion, presupuesto, urgencia y canal para decidir si esto va a ventas o a una cola operativa.',
    sampleInput:
      'Web: "Necesito presupuesto esta semana para automatizar seguimiento de clientes"\nInstagram: "¿Podeis integrar formularios, WhatsApp y CRM?"\nEmail: "Tenemos 3 comerciales y estamos perdiendo leads por respuesta lenta"',
    items: [
      {
        id: 'lead-1',
        source: 'Formulario web',
        company: 'Reformas Norte',
        contact: 'Lucia Gomez',
        payload: 'Necesito presupuesto esta semana para automatizar seguimiento de clientes.',
        amount: 8200,
        priority: 'Alta',
        destination: 'Ventas',
        action: 'Crear oportunidad, asignar llamada y avisar en Slack.',
        intent: 'Presupuesto urgente con intencion comercial clara',
      },
      {
        id: 'lead-2',
        source: 'Instagram',
        company: 'Clinica Lumen',
        contact: 'David Serra',
        payload: '¿Podeis integrar formularios, WhatsApp y CRM sin cambiar el sistema actual?',
        amount: 4600,
        priority: 'Media',
        destination: 'Ventas',
        action: 'Responder, pedir contexto y abrir oportunidad cualificada.',
        intent: 'Consulta comercial con dependencia de integración',
      },
      {
        id: 'lead-3',
        source: 'Email',
        company: 'Hotel Arce',
        contact: 'Marta Prat',
        payload: 'Estamos perdiendo leads por tardar en responder fuera de horario.',
        amount: 5200,
        priority: 'Alta',
        destination: 'Operaciones',
        action: 'Crear diagnóstico operativo y preparar propuesta automatizada.',
        intent: 'Dolor operativo con impacto directo en ventas',
      },
    ],
  },
  {
    id: 'incidents',
    title: 'Incidencias mezcladas con pedidos',
    subtitle: 'Soporte, pedidos y facturacion viviendo en la misma bandeja',
    problem: 'Todo entra por email y el equipo pierde tiempo reenviando, aclarando y persiguiendo al responsable correcto.',
    inputLabel: 'Correos, incidencias y mensajes de clientes',
    outputLabel: 'Ruta operativa, prioridad y siguiente responsable',
    impact: 'Ahorra reenvios manuales y evita que incidencias sensibles se queden sin contexto.',
    assistantPrompt: 'Detecto si el mensaje es queja, soporte, pedido o facturacion para enrutarlo con contexto y urgencia.',
    sampleInput:
      'Email: "Pedido duplicado y error de stock en ERP"\nEmail: "Cancelacion y posible reclamacion por cargos"\nEmail: "Necesito copia de facturas pendientes"',
    items: [
      {
        id: 'incident-1',
        source: 'Email',
        company: 'Distribuciones Soler',
        contact: 'Ivan Soler',
        payload: 'Pedido duplicado y error de stock en ERP. Cliente molesto.',
        priority: 'Alta',
        destination: 'Operaciones',
        action: 'Abrir incidencia critica y notificar al responsable de pedidos.',
        intent: 'Incidencia operativa con impacto en servicio',
      },
      {
        id: 'incident-2',
        source: 'Email',
        company: 'Obra10',
        contact: 'Andres Mora',
        payload: 'Cancelacion de servicio y posible reclamacion por cargos.',
        priority: 'Alta',
        destination: 'Finanzas',
        action: 'Escalar a facturacion y crear alerta de churn/riesgo.',
        intent: 'Riesgo financiero y de retencion',
      },
      {
        id: 'incident-3',
        source: 'Email',
        company: 'Taller Norte',
        contact: 'Carlos Ruiz',
        payload: 'Necesito copia de facturas pendientes y estado de cobros.',
        priority: 'Media',
        destination: 'Finanzas',
        action: 'Preparar resumen de facturas y tarea para administracion.',
        intent: 'Consulta de cobro y documentación',
      },
    ],
  },
  {
    id: 'csv',
    title: 'CSV y exportaciones operativas',
    subtitle: 'Un lote con leads, incidencias y solicitudes mezcladas',
    problem: 'Nadie quiere revisar fila por fila un CSV para decidir que va a ventas, soporte o facturacion.',
    inputLabel: 'CSV / exportaciones periodicas',
    outputLabel: 'Clasificación, prioridad y acciones por lote',
    impact: 'Convierte un archivo plano en una cola priorizada y en tareas claras para el equipo.',
    assistantPrompt: 'Limpio el lote, leo el contenido de cada fila y preparo ruta, prioridad y acción visible.',
    sampleInput:
      'CSV: empresa, canal, mensaje, importe\nReformas Luna, web, presupuesto urgente para seguimiento, 8500\nTaller Norte, email, 120 facturas por revisar, 4200\nDistribuciones Soler, csv, pedido duplicado y queja, 1800',
    items: [
      {
        id: 'csv-1',
        source: 'CSV semanal',
        company: 'Reformas Luna',
        contact: 'Laura Gomez',
        payload: 'Presupuesto urgente para automatizar seguimiento de clientes.',
        amount: 8500,
        priority: 'Alta',
        destination: 'Ventas',
        action: 'Crear oportunidad de alto valor y respuesta prioritaria.',
        intent: 'Nueva demanda comercial con potencial alto',
      },
      {
        id: 'csv-2',
        source: 'CSV semanal',
        company: 'Taller Norte',
        contact: 'Carlos Ruiz',
        payload: '120 facturas pendientes por revisar y clasificar.',
        amount: 4200,
        priority: 'Media',
        destination: 'Finanzas',
        action: 'Generar lote para administracion con resumen de facturas.',
        intent: 'Trabajo administrativo repetitivo',
      },
      {
        id: 'csv-3',
        source: 'CSV semanal',
        company: 'Distribuciones Soler',
        contact: 'Ivan Soler',
        payload: 'Pedido duplicado y queja por error de stock.',
        amount: 1800,
        priority: 'Alta',
        destination: 'Operaciones',
        action: 'Crear incidencia prioritaria y resumen de contexto.',
        intent: 'Incidencia operativa urgente',
      },
    ],
  },
];

export const stageCopy = [
  { key: 'ingest', label: 'Entra', description: 'Normaliza canales y lote', icon: Mail },
  { key: 'interpret', label: 'Interpreta', description: 'Lee intencion, importe y urgencia', icon: ScanSearch },
  { key: 'route', label: 'Decide', description: 'Elige destino, prioridad y responsable', icon: Route },
  { key: 'action', label: 'Actua', description: 'Crea resumen, tarea y actualizacion', icon: Workflow },
] as const;
